UPDATE device SET name='电站2逆变器1' WHERE id='dev001';
UPDATE device SET name='电站2逆变器2' WHERE id='dev002';
UPDATE device SET name='电站2逆变器3' WHERE id='dev003';
UPDATE device SET name='电站2电表1', factory='海科' WHERE id='dev004';
UPDATE device SET name='电站4逆变器1' WHERE id='dev005';
UPDATE device SET name='电站4逆变器2' WHERE id='dev006';
UPDATE device SET name='电站4电表1', factory='海科' WHERE id='dev007';
UPDATE device SET name='电站3逆变器1' WHERE id='dev008';
UPDATE device SET name='电站3逆变器2' WHERE id='dev009';
UPDATE device SET name='电站3电表1', factory='海科' WHERE id='dev010';
UPDATE device SET name='电站5逆变器1' WHERE id='dev011';
UPDATE device SET name='电站5逆变器2' WHERE id='dev012';
UPDATE device SET name='电站5电表1', factory='海科' WHERE id='dev013';
UPDATE device SET name='电站6逆变器1' WHERE id='dev014';
UPDATE device SET name='电站6电表1', factory='海科' WHERE id='dev015';
UPDATE device SET name='电站7逆变器1' WHERE id='dev016';
UPDATE device SET name='电站7电表1', factory='海科' WHERE id='dev017';
UPDATE device SET name='电站8逆变器1' WHERE id='dev018';
UPDATE device SET name='电站8逆变器2' WHERE id='dev019';
UPDATE device SET name='电站8电表1', factory='海科' WHERE id='dev020';
UPDATE device SET name='电站9逆变器1' WHERE id='dev021';
UPDATE device SET name='电站9逆变器2' WHERE id='dev022';
UPDATE device SET name='电站9逆变器3' WHERE id='dev023';
UPDATE device SET name='电站9电表1', factory='海科' WHERE id='dev024';
UPDATE device SET name='电站10逆变器1' WHERE id='dev025';
UPDATE device SET name='电站10逆变器2' WHERE id='dev026';
UPDATE device SET name='电站10电表1', factory='海科' WHERE id='dev027';
UPDATE device SET name='电站11逆变器1' WHERE id='dev028';
UPDATE device SET name='电站11逆变器2' WHERE id='dev029';
UPDATE device SET name='电站11逆变器3' WHERE id='dev030';
UPDATE device SET name='电站11电表1', factory='海科' WHERE id='dev031';
UPDATE device SET name='电站12逆变器1' WHERE id='dev032';
UPDATE device SET name='电站12逆变器2' WHERE id='dev033';
UPDATE device SET name='电站12电表1', factory='海科' WHERE id='dev034';